version: '3'

tasks:
  lab1:
    desc: Compile lab1.tex to pdf
    sources:
      - src/lab1/*
    cmds:
      - tectonic "./src/lab1/lab1.tex" -Z search-path="src" --outdir "pdf"

  lab2:
    desc: Compile lab2.tex to pdf
    sources:
      - src/lab2/*
    cmds:
      - tectonic "./src/lab2/lab2.tex" -Z search-path="src" -Z shell-escape --outdir "pdf"

  lab3:
    desc: Compile lab3.tex to pdf
    sources:
      - src/lab3/*
    cmds:
      - tectonic "./src/lab3/lab3.tex" -Z search-path="src" -Z shell-escape --outdir "pdf"
